project_id = "qpsappgemzrmgzunvcho"

[functions.ai-chat]
verify_jwt = false

[functions.google-drive-auth]
verify_jwt = false

[functions.google-drive-files]
verify_jwt = false

[functions.google-drive-content]
verify_jwt = false

[functions.parse-pdf]
verify_jwt = false